-- Initialize items of table: DEPARTMENT

INSERT INTO DEPARTMENT (ID, NAME)
VALUES (1, 'DEPARTMENT-1');
INSERT INTO DEPARTMENT (ID, NAME)
VALUES (2, 'DEPARTMENT-2');
INSERT INTO DEPARTMENT (ID, NAME)
VALUES (3, 'DEPARTMENT-3');
INSERT INTO DEPARTMENT (ID, NAME)
VALUES (4, 'DEPARTMENT-4');
INSERT INTO DEPARTMENT (ID, NAME)
VALUES (5, 'DEPARTMENT-5');

-- Initialize items of table: STUDENT

INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (1, 'FNAME-1', 'LNAME-1', 'E-MAIL-1@GMAIL.COM', '1988-05-10', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (2, 'FNAME-2', 'LNAME-2', 'E-MAIL-2@GMAIL.COM', '1988-05-11', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (3, 'FNAME-3', 'LNAME-3', 'E-MAIL-3@GMAIL.COM', '1988-05-12', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (4, 'FNAME-4', 'LNAME-4', 'E-MAIL-4@GMAIL.COM', '1988-05-13', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (5, 'FNAME-5', 'LNAME-5', 'E-MAIL-5@GMAIL.COM', '1988-05-14', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (6, 'FNAME-6', 'LNAME-6', 'E-MAIL-6@GMAIL.COM', '1988-05-15', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (7, 'FNAME-7', 'LNAME-7', 'E-MAIL-7@GMAIL.COM', '1988-05-16', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (8, 'FNAME-8', 'LNAME-8', 'E-MAIL-8@GMAIL.COM', '1988-05-17', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (9, 'FNAME-9', 'LNAME-9', 'E-MAIL-9@GMAIL.COM', '1988-05-18', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (10, 'FNAME-10', 'LNAME-10', 'E-MAIL-10@GMAIL.COM', '1988-05-19', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (11, 'FNAME-11', 'LNAME-11', 'E-MAIL-11@GMAIL.COM', '1988-05-20', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (12, 'FNAME-12', 'LNAME-12', 'E-MAIL-12@GMAIL.COM', '1988-05-21', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (13, 'FNAME-13', 'LNAME-13', 'E-MAIL-13@GMAIL.COM', '1988-05-22', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (14, 'FNAME-14', 'LNAME-14', 'E-MAIL-14@GMAIL.COM', '1988-05-23', '111111', 'ROLE_USER', 1);
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (15, 'FNAME-15', 'LNAME-15', 'E-MAIL-15@GMAIL.COM', '1988-05-24', '111111', 'ROLE_USER', 1);

-- Initialize items of table: SUBJECT

INSERT INTO SUBJECT (ID, NAME)
VALUES (1, 'SUBJECT-1');
INSERT INTO SUBJECT (ID, NAME)
VALUES (2, 'SUBJECT-2');
INSERT INTO SUBJECT (ID, NAME)
VALUES (3, 'SUBJECT-3');
INSERT INTO SUBJECT (ID, NAME)
VALUES (4, 'SUBJECT-4');
INSERT INTO SUBJECT (ID, NAME)
VALUES (5, 'SUBJECT-5');

-- Initialize items of table: SUBJECT_DEPARTMENT

INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (1, 1);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (2, 1);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (3, 1);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (4, 1);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (5, 1);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (1, 2);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (2, 2);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (3, 2);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (4, 2);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (5, 2);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (1, 3);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (2, 3);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (3, 3);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (4, 3);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (5, 3);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (1, 4);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (2, 4);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (3, 4);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (4, 4);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (5, 4);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (1, 5);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (2, 5);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (3, 5);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (4, 5);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES (5, 5);

-- Initialize items of table: SUBJECT_STUDENT

INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 1);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 1);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 1);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 1);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 1);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 2);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 2);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 2);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 2);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 2);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 3);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 3);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 3);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 3);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 3);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 4);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 4);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 4);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 4);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 4);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 5);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 5);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 5);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 5);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 5);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 6);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 6);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 6);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 6);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 6);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 7);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 7);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 7);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 7);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 7);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 8);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 8);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 8);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 8);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 8);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 9);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 9);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 9);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 9);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 9);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 10);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 10);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 10);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 10);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 10);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 11);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 11);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 11);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 11);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 11);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 12);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 12);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 12);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 12);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 12);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 13);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 13);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 13);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 13);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 13);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 14);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 14);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 14);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 14);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 14);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (1, 15);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (2, 15);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (3, 15);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (4, 15);
INSERT INTO SUBJECT_STUDENT (SUB_ID, STUD_ID)
VALUES (5, 15);

-- Initialize items of table: MARKS

INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (1, 4, '2018-05-15', 12, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (2, 2, '2018-05-05', 12, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (3, 2, '2018-05-14', 11, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (4, 5, '2018-05-24', 7, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (5, 1, '2018-05-09', 6, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (6, 4, '2018-05-01', 1, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (7, 4, '2018-05-31', 5, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (8, 5, '2018-05-03', 10, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (9, 3, '2018-04-014', 14, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID)
VALUES (10, 3, '2018-06-06', 15, 1);