INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'TEST_DEPARTMENT');
INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES (1, 'FIRST-NAME', 'LAST-NAME', 'EMAIL', '1970-01-01', 'PASSWORD', 'USER', 1);
INSERT INTO SUBJECT (ID, NAME) VALUES (1, 'SUBJECT');