-- Clear Mark table
DELETE FROM MARK;
-- Add Department
INSERT INTO DEPARTMENT (NAME) VALUES ('TEST_DEPARTMENT');
-- Add Student
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, EMAIL, BIRTHDAY, PASSWORD, ROLE, DEP_ID)
VALUES ('FIRST-NAME', 'LAST-NAME', 'EMAIL', '1970-01-01', 'PASSWORD', 'USER',
        (SELECT ID FROM DEPARTMENT WHERE NAME = 'TEST_DEPARTMENT'));
-- Add Subject
INSERT INTO SUBJECT (NAME) VALUES ('SUBJECT');