-- Add Faculty
INSERT INTO FACULTY (NAME) VALUES ('FACULTY');
-- Add Subjects
INSERT INTO SUBJECT(NAME) VALUES ('SUBJECT');
INSERT INTO SUBJECT(NAME) VALUES ('SUBJECT-2');
-- Link Subjects with Faculty
INSERT INTO SUBJECT_FACULTY (SUB_ID, FAC_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT'),
        (SELECT ID FROM FACULTY WHERE NAME = 'FACULTY'));
INSERT INTO SUBJECT_FACULTY (SUB_ID, FAC_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT-2'),
        (SELECT ID FROM FACULTY WHERE NAME = 'FACULTY'));
-- Add Student
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, PASSWORD, EMAIL, BIRTHDAY, ROLE, FAC_ID)
VALUES ('FIRST-NAME', 'LAST-NAME', 'PASSWORD', 'EMAIL', '2000-01-01', 'USER',
        (SELECT ID FROM FACULTY WHERE NAME = 'FACULTY'));
-- Link Subjects with Student
INSERT INTO SUBJECT_STUDENT (STUD_ID, SUB_ID)
VALUES ((SELECT ID FROM STUDENT WHERE FIRST_NAME = 'FIRST-NAME' AND LAST_NAME ='LAST-NAME'),
        (SELECT ID FROM SUBJECT WHERE NAME ='SUBJECT'));
INSERT INTO SUBJECT_STUDENT (STUD_ID, SUB_ID)
VALUES ((SELECT ID FROM STUDENT WHERE FIRST_NAME = 'FIRST-NAME' AND LAST_NAME ='LAST-NAME'),
        (SELECT ID FROM SUBJECT WHERE NAME ='SUBJECT-2'));
-- Add Grades
INSERT INTO GRADE (GRADE, PERCENT, DATE, STUD_ID, SUBJ_ID)
VALUES ('C', 78, '2018-04-01', (SELECT ID FROM STUDENT WHERE FIRST_NAME = 'FIRST-NAME' AND LAST_NAME ='LAST-NAME'),
        (SELECT ID FROM SUBJECT WHERE NAME ='SUBJECT'));
INSERT INTO GRADE (GRADE, PERCENT, DATE, STUD_ID, SUBJ_ID)
VALUES ('D', 65, '2018-04-14',
        (SELECT ID FROM STUDENT WHERE FIRST_NAME = 'FIRST-NAME' AND LAST_NAME ='LAST-NAME'),
        (SELECT ID FROM SUBJECT WHERE NAME ='SUBJECT'));
INSERT INTO GRADE (GRADE, PERCENT, DATE, STUD_ID, SUBJ_ID)
VALUES ('A', 91, '2018-06-04',
        (SELECT ID FROM STUDENT WHERE FIRST_NAME = 'FIRST-NAME' AND LAST_NAME ='LAST-NAME'),
        (SELECT ID FROM SUBJECT WHERE NAME ='SUBJECT'));