-- Add Faculty
INSERT INTO FACULTY (NAME) VALUES ('FACULTY');
-- Add Subject
INSERT INTO SUBJECT(NAME) VALUES ('SUBJECT-1');
INSERT INTO SUBJECT(NAME) VALUES ('SUBJECT-2');
-- Link Subject with Faculty
INSERT INTO SUBJECT_FACULTY (SUB_ID, FAC_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT-1'),
        (SELECT ID FROM FACULTY WHERE NAME = 'FACULTY'));
INSERT INTO SUBJECT_FACULTY (SUB_ID, FAC_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT-2'),
        (SELECT ID FROM FACULTY WHERE NAME = 'FACULTY'));