-- Add Department
INSERT INTO DEPARTMENT (NAME) VALUES ('DEPARTMENT');
-- Add Subject
INSERT INTO SUBJECT(NAME) VALUES ('SUBJECT-1');
INSERT INTO SUBJECT(NAME) VALUES ('SUBJECT-2');
-- Link Subject with Department
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT-1'),
        (SELECT ID FROM DEPARTMENT WHERE NAME = 'DEPARTMENT'));
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT-2'),
        (SELECT ID FROM DEPARTMENT WHERE NAME = 'DEPARTMENT'));