-- Add Subject
INSERT INTO SUBJECT (NAME) VALUES ('SUBJECT');
-- Add Faculty
INSERT INTO FACULTY (NAME) VALUES ('FACULTY-1');
INSERT INTO FACULTY (NAME) VALUES ('FACULTY-2');
-- Link Subjects with Faculty
INSERT INTO SUBJECT_FACULTY (SUB_ID, FAC_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT'),
        (SELECT ID FROM FACULTY WHERE NAME = 'FACULTY-1'));
INSERT INTO SUBJECT_FACULTY (SUB_ID, FAC_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT'),
        (SELECT ID FROM FACULTY WHERE NAME = 'FACULTY-2'));