INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'DEPARTMENT');

INSERT INTO SUBJECT(ID, NAME) VALUES (1, 'SUBJECT-1');
INSERT INTO SUBJECT(ID, NAME) VALUES (2, 'SUBJECT-2');

INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID) VALUES (1, 1);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID) VALUES (2, 1);