-- Add Subject
INSERT INTO SUBJECT (NAME) VALUES ('SUBJECT');
-- Add Department
INSERT INTO DEPARTMENT (NAME) VALUES ('DEPARTMENT-1');
INSERT INTO DEPARTMENT (NAME) VALUES ('DEPARTMENT-2');
-- Link Subjects with Department
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT'),
        (SELECT ID FROM DEPARTMENT WHERE NAME = 'DEPARTMENT-1'));
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID)
VALUES ((SELECT ID FROM SUBJECT WHERE NAME = 'SUBJECT'),
        (SELECT ID FROM DEPARTMENT WHERE NAME = 'DEPARTMENT-2'));