INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'DEPARTMENT');

INSERT INTO SUBJECT(ID, NAME) VALUES (1, 'SUBJECT');
INSERT INTO SUBJECT(ID, NAME) VALUES (2, 'SUBJECT-2');

INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID) VALUES (1, 1);
INSERT INTO SUBJECT_DEPARTMENT (SUB_ID, DEP_ID) VALUES (2, 1);

INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, PASSWORD, EMAIL, BIRTHDAY, ROLE, DEP_ID)
VALUES (1, 'FIRST-NAME', 'LAST-NAME', 'PASSWORD', 'EMAIL', '2000-01-01', 'USER', 1);

INSERT INTO SUBJECT_STUDENT (STUD_ID, SUB_ID) VALUES (1, 1);
INSERT INTO SUBJECT_STUDENT (STUD_ID, SUB_ID) VALUES (1, 2);

INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID) VALUES (1, 2, '2018-04-01', 1, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID) VALUES (2, 3, '2018-04-14', 1, 1);
INSERT INTO MARK (ID, VALUE, DATE, STUD_ID, SUBJ_ID) VALUES (3, 3, '2018-06-04', 1, 1);